<?php
/**
 * Adawwa self-hosted contact admin — config template.
 * Generated by Adawwa. Fill DB credentials, then open /contact-admin/install.php once.
 * install.php generates a random admin password and shows it on screen.
 */
return [
  'db' => [
    'host' => '127.0.0.1',
    'port' => 3306,
    'name' => 'portfolio_contact',
    'user' => 'root',
    'pass' => '',
  ],
  'admin' => [
    'username' => '{{ADMIN_USERNAME}}',
  ],
  'security' => [
    'session_name' => 'adawwa_contact_admin',
    // Legacy single-bucket keys kept for compatibility; submit uses multi-tier limits in lib.php
    'rate_limit' => 3,
    'rate_window_sec' => 900,
  ],
];
