import fs from 'fs/promises';
import path from 'path';
import Handlebars from 'handlebars';
import archiver from 'archiver';
import { createWriteStream } from 'fs';
import { env } from '../config';
import { PortfolioRow, toTemplateContext } from './portfolioMapper';

async function copyDir(src: string, dest: string) {
  await fs.mkdir(dest, { recursive: true });
  const entries = await fs.readdir(src, { withFileTypes: true });
  for (const entry of entries) {
    const from = path.join(src, entry.name);
    const to = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      await copyDir(from, to);
    } else if (entry.name.endsWith('.hbs')) {
      continue;
    } else {
      await fs.copyFile(from, to);
    }
  }
}

export async function renderPortfolioFiles(row: PortfolioRow, workDir: string) {
  let slug = row.template_slug || 'minimal';
  let templateDir = path.join(env.templatesPath, slug);
  let exists = await fs
    .access(templateDir)
    .then(() => true)
    .catch(() => false);
  if (!exists) {
    slug = 'minimal';
    templateDir = path.join(env.templatesPath, slug);
    exists = await fs
      .access(templateDir)
      .then(() => true)
      .catch(() => false);
  }
  if (!exists) {
    throw new Error(`Template not found: ${slug}`);
  }

  await fs.mkdir(workDir, { recursive: true });
  await copyDir(templateDir, workDir);

  const hbsPath = path.join(templateDir, 'index.html.hbs');
  const source = await fs.readFile(hbsPath, 'utf8');
  const template = Handlebars.compile(source);
  const html = template(toTemplateContext(row));
  await fs.writeFile(path.join(workDir, 'index.html'), html, 'utf8');

  const readme = `# ${row.full_name || 'Portfolio'}

Static single-page portfolio generated by Portfolio Generator.

## Run locally

Open \`index.html\` in a browser, or serve the folder:

\`\`\`bash
npx serve .
\`\`\`

## Deploy

Upload this folder to Netlify, Vercel, GitHub Pages, or any static host / cPanel \`public_html\`.

## SEO

Host this on **your own domain** for search ranking. A link on the generator site at \`/portfolio/...\` is for sharing only and is not meant for SEO.
`;
  await fs.writeFile(path.join(workDir, 'README.md'), readme, 'utf8');
}

export async function zipDirectory(sourceDir: string, zipPath: string): Promise<number> {
  await fs.mkdir(path.dirname(zipPath), { recursive: true });
  return new Promise((resolve, reject) => {
    const output = createWriteStream(zipPath);
    const archive = archiver('zip', { zlib: { level: 9 } });
    output.on('close', () => resolve(archive.pointer()));
    archive.on('error', reject);
    archive.pipe(output);
    archive.directory(sourceDir, false);
    archive.finalize();
  });
}
